### ISSUE TITLE
Statistics page and API

### ISSUE THREAD

**Issue by finnbear** [SoftbearStudios/mk48#103]
There should be a page (and required API) to view usage statistics

**Comment by thatretrodev** [comment]
I like that idea, because I find that it's always a good idea to have an API.

**Comment by finnbear** [comment]
> I find that it's always a good idea to have an API.

The API referenced here is the bare minimum necessary to read statistics from the database. If you mean an API to create custom bots, that's this issue: #82 (TLDR: Anyone can already connect to the server and write a bot, but there isn't much code to help you do it)
