### ISSUE TITLE
Multi-thread Physics 

### ISSUE THREAD

**Issue by caibear** [SoftbearStudios/mk48#104]
Currently the entity against entity calculations such as collision or tracking are done on a single thread. This is a major bottleneck for scaling the server to one with more than 2 cores. It uses half of the update with 10k bots utilizing 12 cores (this number would be different for socket clients). Even if we don't plan to increase the size of the official servers I think this is a good idea for code completeness.

The solution is to do the iteration over multiple threads and collect the results such as entity deletions/tracking movements with channels and apply them at the end. We also need to buffer all entity additions somehow, possibly in `World.AddEntity`. Also this raises the question of how we should fix the current torpedo/missile tracking code which is currently dependent on iteration order.

**Comment by finnbear** [comment]
Done, thanks to https://github.com/rayon-rs/rayon
