### ISSUE TITLE
Ship with single weapon deselected weapon

### ISSUE THREAD

**Issue by Ohmugin** [SoftbearStudios/mk48#133]
**Describe the bug**

1. Be G-5 (freshly logged in)
2. Attack Zubr with both torpedoes (held down space)
3. Zubr doesn't sink, waiting for reload
4. Torpedoes reloaded (2/2)
5. **New torpedoes won't launch!**

I tried space, E, clicking, any launch angle - no luck.
Browser console had nothing except FPS messages.
Eventually noticed that the single entry in the weapon list left-bottom does not have a gray box around it! Clicked on it, it was selected and I was able to launch torpedoes again!
For some reason it was deselected, even though I was not able to deselect it again manually neither by clicking or pressing tab.
I cannot reliably reproduce it. Maybe it didn't like that I held down space all the time?

This is admittedly a very minor bug, but might still be useful to have a reference

**Expected behavior**

Weapon is never deselected.

**Additional context (optional)**

Used Chromium Edge 91.0.864.48 directly in mk48.io

**Comment by finnbear** [comment]
Hi, thanks for the detailed report. There is one way, that I intentionally
added, to deselect all weapons and that is to press a number key that
exceeds that of the highest weapon. I'd like to keep the disarm-all option,
as a way to prevent unintentionally firing on your non-fleet friends/your
base. One fix would be to disable this method of disarmament, or limit it
to a single key like the zero number. Another mitigation would be to play a
sound when arming and disarming (next update brings various sounds) to
alert you. It should definitely be more obvious (and documented) what the
behavior is 😀

**Comment by finnbear** [comment]
I decided to completely disable the ability to disarm all weapons, until I arrive at a clearer solution.

**Comment by Ohmugin** [comment]
Thanks for clearing that up!
One option would be a "prohibited" semi-transparent overlay (🚫) with text. Or some kind of lock symbol. The issue for me personally was the very subtle background color
