### ISSUE TITLE
Active sensors should allow you to see more terrain while underwater.

### ISSUE THREAD

**Issue by finnbear** [SoftbearStudios/mk48#140]
As a submerged sub, view is very restrictive. This would incentivize use of active sensors and improve vision. It wouldn't significantly affect visibility in any other situation.

Suggested by: Carlsons1938#0639

**Comment by caibear** [comment]
Closing as terrain limitations were recently removed. Players how receive terrain for their whole screen (up to aspect ratio of 2) no matter what.
