### ISSUE TITLE
Recovering Sunken Ships

### ISSUE THREAD

**Issue by thatretrodev** [SoftbearStudios/mk48#142]
I think that being able to Recover Sunken Ships might be something great for Mk48.io.
Here's my (simple) idea on how that would work:
- Sunken Ship gets Found and Recovered (Maybe using an item, or maybe using a Ship designed for Recovering other Ships)
- Recovered Ship parts get collected (Maybe this could give the player XP points?)

As for implementing it, I'm not sure about how the player would actually recover a sunken ship on the client-side but on the server-side sunken ships could be stored for a couple minutes to give other players time to recover the ships.

**Comment by finnbear** [comment]
This is a cool idea. I'm not sure it solves any serious problem with the game to justify the added complexity, though.

**Comment by thatretrodev** [comment]
> This is a cool idea. I'm not sure it solves any serious problem with the game to justify the added complexity, though.

While in most cases you'd be right, I find it quite useful to be able to put in a lot of effort (but not as much effort as it took to get the ship I'd recover) to recover the ship I was using post-respawn.

**Comment by thatretrodev** [comment]
This idea hasn't been implemented yet, and this issue is old.

I'm closing this issue until it is useful again.
