### ISSUE TITLE
Cencership

### ISSUE THREAD

**Issue by JoeyMeepLand** [SoftbearStudios/mk48#153]
**When Ever i type number like 900 and some other it cencers the 00 to stars. if i add more zero is cencers it all.**

**Comment by caibear** [comment]
Mk48 uses [rustrict](https://github.com/finnbear/rustrict) as its profanity filter.
Please reopen this issue there.

**Comment by finnbear** [comment]
This particular problem was fixed in a recent `rustrict` update, and that fix has now been deployed :)
