### ISSUE TITLE
Doesn't work in palemoon

### ISSUE THREAD

**Issue by l29ah** [SoftbearStudios/mk48#160]
**Describe the bug**
Empty blue screen at mk48.io. The console says:
```
ReferenceError: BigUint64Array is not defined[Learn More]  
bundle.js:1:407574
```

**Expected behavior**
Working.

**Additional context (optional)**
Palemoon here.

**Comment by finnbear** [comment]
Thanks for the report!

This isn't the first time `BigUint64Array` got in the way of compatibility (it prevents my old iPad from working too). The good news is that, last time, I was able to find and fix the code to remove the `BigUint64Array` dependency. I'll see what I can do for the next update.

**Comment by finnbear** [comment]
Update: I've removed the `BigUint64Array` dependency in the latest update. Please open a new issue if there are any other issues with running in Palemoon!
