### ISSUE TITLE
Ship switching abused

### ISSUE THREAD

**Issue by mitm001** [SoftbearStudios/mk48#168]
Its pretty obvious that some players have figured out a way to switch between ships at will. Not just by saving a level and switching right before sinking to a larger ship, but switching several times in a row. I witnessed a switch from level 3 to level 4 warship to level 10 Nimitz to stop from being sunk by me. Not just one time but several times.

**Expected behavior**

You cannot switch period to stop a sinking. A timer should be set from last damage to prevent abuse of ship upgrading. Figure out how they are accessing the ship upgrade menu like that would also be a suggestion. 

If this is allowed, I would like to know how they do it.

**Comment by finnbear** [comment]
We recently (a month ago) took a step towards mitigating this by reducing the damage repaired due to upgrading. In general, our intention is for upgrading promptly after earning the required points to repair some damage, but we don't want to encourage players to strategically delay upgrading to win battles.

You mention you would like to know how players do this, and it is pretty simple and (despite the potential for abuse) is not in violation of any rule. They just save up lots of points, and then click an upgrade in the normal upgrade menu any time they are close to death.

Any solution we adopt in the future should obey the following principles:
- the problem that must be solved is the extreme unfairness players face when their enemy strategically upgrades during combat (especially if they upgrade more than once)
- upgrading promptly after earning the points or when not engaged in combat is not abusive and should not be affected

I see a few potential solutions:
- Add upgrade cooldown, limiting players to one upgrade in a 10 second period
- If a player does upgrade more than once in 30 seconds, all but first upgrade don't regenerate health
- make upgrades cost exponentially more, to make the strategy economically unviable

**Comment by mitm001** [comment]
Alternatively you could force upgrading by stopping exp gain until the upgrade is done. This is typically how its done. Its a simple If statement check for exp gain that takes all of 15 seconds to write.

**Comment by finnbear** [comment]
> Alternatively you could force upgrading by stopping exp gain until the upgrade is done. This is typically how its done. Its a simple If statement check for exp gain that takes all of 15 seconds to write.

This would easily fix the problem but prevent the challenge of getting on the leaderboard while as a low level ship. I'd like to preserve that usecase.

**Comment by mitm001** [comment]
Set the timer for one minute to upgrade before exp stops. 

You can also stop using exp for determining the leader and instead use kill levels or something like that. 

A ship sinks level 1 =1 point, level 10 = 10 points. Reset to 0 upon sinking. 

You can tweak the system to account for a lower level ship sinking a higher level opponent and vice versa as long as each hit is tracked so the person doing most damage gets more points. Reset the damage counter if they regain full health. 

I think its more impressive that I as a level one have taken out 2 of 5 level 10s in a fleet with a 1 level torpedo boat. That should be worth more than a group of level 10 carriers, subs, and destroyers attacking every level 1- 3 as is now being done. 

The switching today saved several level 10s from me with a level 3 sub kicking their buts. It didn't save them all but enough to get real aggravating as that is hard work.

**Comment by mitm001** [comment]
Another simple fix, remove any health gains period. Keep the same damage prior to switch. Problem solved...

**Comment by finnbear** [comment]
> Another simple fix, remove any health gains period. Keep the same damage prior to switch. Problem solved...

You make a good argument. I'm inclined to reduce health gains once again, and ultimately increase the cost of leveling up (more) exponentially.

I am surprised by the frequency that you observe multiple-delayed-upgrades, though. They are not intended to be easy to pull off, as they require gathering many points in advance.

**Comment by mitm001** [comment]
> I am surprised by the frequency that you observe multiple-delayed-upgrades, 

Its so common I attack every level 2+ now as they use the low level to travel fast and search for bigger targets. There are some newer players I usually don't attack because they seemed to be struggling to gain levels and I felt sorry for them but lately I noticed even they are now trying the same tactic. 

Most start camping out on a exp spawn station (not sure what they are called) with a level 2 ship to build exp, attacking low level easy targets also.  The next stage appears to be using a level 4 ship showing but they are able to upgrade up to level 7. The next stage looks to be 7-10 range, with level 7 showing. 

I don't understand the logic of healing them when they upgrade. You can recover health quickly enough without that feature as it is. If you remove the health bonus and allow only one upgrade you would have a complete solution. 

Once they do upgrade, keep the upgrade screen hidden unless they gain another level. That also forces them to be more tactical in their thinking. You can bank exp but you only get one upgrade.

**Comment by mitm001** [comment]
I found out what seems to be the common way of gathering exp is so they can switch at will. They form a fleet then find a area with three or more exp spawns near each other and sit there sucking up exp. Eventually they are all level 9 so you cant dislodge them. Then they go roaming and switch back and forth. I had at least a half dozen 9 levels on the ropes and they switched back and forth until their buddies could sink me. They didn't stand a chance otherwise.  One guy named Son camped all day like that. Last I looked before he logged off he was pushing 40k and hadn't even sunk a ship. 

You can pretty much bank on any level 9 doing this. Definitely everyone in the top slots of leader board are doing it. 

Another suggestion is to track exp from sinking ships and exp from chests. Limit exp per level for chests to 50% of whats needed to level so you force them to take risks rather than cheat their way to the top of the leader board. The leader board is really meaningless at this point as it doesn't reflect skill, just cheating and exp campers.

**Comment by finnbear** [comment]
In today's (or rather yesterday's) update, I made the following change:
> Remove health regeneration when upgrading to below your full potential.

In other words, if you can upgrade to level 8, upgrading to level 7 won't change your health percentage.

This should not affect normal play, but remove most of the benefit of a delayed upgrade spree.

**Comment by mitm001** [comment]
> won't change your health percentage.

To clarify, they would still have the same hp remaining as before the switch?

**Comment by mitm001** [comment]
I noticed the difference yesterday but wasn't sure, this seems to of fixed the problem. Very little switching happening today compared to before. More manageable when it does happen. 

A side bonus is they go from level 4 or 5 to 9 so its much more satisfying if you succeed in the attack.

**Comment by finnbear** [comment]
> To clarify, they would still have the same hp remaining as before the switch?

The actual invariant is the health **percent**, i.e. what is displayed by the health bar. That means if you have 40% health (say 2.0 absolute hp) and you upgrade to a much bigger ship (but not the highest level available) that, by extension, has more max health, you will still have 40% health, but your absolute hp might be 3.0.

(The opposite is true too. If you upgrade to a smaller ship with less max health, your absolute hp would go down)

> I noticed the difference yesterday but wasn't sure, this seems to of fixed the problem. Very little switching happening today compared to before. More manageable when it does happen.

I think it's too early for a conclusive result, but I'm happy the experience was better yesterday.

> A side bonus is they go from level 4 or 5 to 9 so its much more satisfying if you succeed in the attack.
