### ISSUE TITLE
High level Sub torpedos too weak

### ISSUE THREAD

**Issue by mitm001** [SoftbearStudios/mk48#169]
Sub torpedoes are to weak by about 15%. At higher levels a sub cannot defeat another ship by unleashing all its available payload into any other ship of the same level.

I unloaded entire payload of Sea Wolf into a Nimitz  and still had to follow up with 3 more torpedo's. Its even worse against the other ships with same level. Even the next lower level sub, unloading every weapon it has cannot sink a max level ship. 

**Expected behavior**

There is no ship ever built that could sustain that many hits from an advanced torpedo or 10 missiles and remain floating. Its not physically possible. 

This unbalance means in one on one situations its nearly impossible to sink a max level ship with a sub. You will on almost every occasion be sunk with their counter attacks, which are way to powerful in their own right. 

I do succeed occasionally but it takes some stupid mistake on their part or catching them with low health for it to happen. If they don't panic and simply counter attack they win every battle. 

Tweaking the torpedoes so that firing a maxed out payload sinks any ship of the same level would be more appropriate. Evidently, others feel the same way as I have seen it discussed on the Radio.

**Comment by finnbear** [comment]
> There is no ship ever built that could sustain that many hits from an advanced torpedo or 10 missiles and remain floating. Its not physically possible.

This is true, but not viable from the ship's perspective in the context of gameplay. One of the main lines of defenses real ships have against subs is distance (over-the-horizon range). Torpedoes are slow and have finite range. However, in Mk48.io, the top-down view forces engagements to take place at a much shorter range (potato-cannon range). If torpedo salvos reliably killed big ships, then big ships would be hunted down to extinction. The best solution I could come up with is to make torpedoes do serious, but not necessarily fatal, damage. That way, engagements go from being almost instant to ~30 seconds, giving the big ship player time to fight back.

**Comment by mitm001** [comment]
I will try the center hit. I wasn't aware of the difference.

**Comment by mitm001** [comment]
Belly shots do work better. Closing this as its not a problem.
