### ISSUE TITLE
Ability to lock panels like the armament panel.

### ISSUE THREAD

**Issue by mitm001** [SoftbearStudios/mk48#172]
It would be nice to be able to toggle an individual panel not to minimize, such as the arms panel in the lower left. It's not to hard to hit the name and minimize in the heat of battle. 

This could be something you have under settings when you get user accounts up and running.

**Comment by finnbear** [comment]
Thanks for pointing this out!

We have actually recognized for about a month now that the ability to close the armament panel is a long-standing footgun, *especially* on touchscreen devices and *especially* for new players.

The ability to close it is planned to be removed, except in cinematic mode (which is currently a setting).

**Comment by caibear** [comment]
Fixed in latest update (armament panel can't be closed).
