### ISSUE TITLE
sub to ship switch

### ISSUE THREAD

**Issue by mitm001** [SoftbearStudios/mk48#177]
Looks like a new abuse is now happening. The latest is to attack with a sub and move towards target then switch to carrier if its obvious they are toast. The carrier is under water so you get sunk as it moves to surface. Second time today.

Expected behavior would be make it so you must surface to switch from sub to ship.

**Comment by finnbear** [comment]
I can understand how this could be annoying, but I don't consider isolated incidents of using intentionally-added features (damage from collision, and rising  to one's advantage as abuse.

However, this type of combat shouldn't be too common. I've always wanted to add some metrics to catalog how each and every player dies. If we were to add those metrics, and "being uplifted by a rising aircraft carrier" accounted for more than ~1-5% of deaths, that would prompt us to take some action. For now, while I have seen it happen, I don't think it is out-of-control.

**Comment by mitm001** [comment]
The ships are under water though after switch. An aircraft carrier 400m under water rising is kinda not normal. Makes perfect sense making subs surface to switch to a surface vessel though.

**Comment by mitm001** [comment]
One hit away from sinking sub again and they switch to destroyer level 8 under water. I watch in amazement as they get to sink me with a destroyer counter attack as they float to the surface from 400 meters deep. Absolutely makes perfect sense. 

It is not a isolated event. its being used regularly now. One guy even did it under the ice sheet. Was kinda funny watching him blow up but never the less its not as rare as you think it is.

**Comment by caibear** [comment]
Fixed in latest update.
