### ISSUE TITLE
Rocket torpedos to unreliable.

### ISSUE THREAD

**Issue by mitm001** [SoftbearStudios/mk48#181]
I have spent a considerable amount of time testing rocket torpedoes and am wondering why its so difficult to get them to acquire the target unless its a broadside attack?

They do very little damage anyway, similar to the deck gun on a level 2 sub so why the handicap?

I would think similar performance as the level 8 rockets would be appropriate myself. Currently your lucky if 25% find the target.

**Comment by caibear** [comment]
Fixed in latest update.
