### ISSUE TITLE
游戏操作异常

### ISSUE THREAD

**Issue by SadEPa0628** [SoftbearStudios/mk48#216]
**Describe the bug**

我无法控制我的船移动和发射导弹，并且我无法再聊天区说话，有时候会严重到看不到船只或者不受控制地到处漂移甚至直接无缘无故的死掉。并且这些情况是通常的，就好像能够正常操作才是不正常的。
**Expected behavior**

我希望能够修复上述问题，让我能够正常操作。

**Comment by finnbear** [comment]
Hello! You may be experiencing network lag or a bug in the game (please send a screenshot of Inspect Element Console). It's also possible that you are not using the right input controls (WASD/arrows/right-click and hold).

--- google translate ---

你好！您可能遇到网络延迟或游戏错误（请发送 Inspect Element Console 的屏幕截图）。也有可能您没有使用正确的输入控件（WASD/箭头/右键单击并按住）。

**Comment by SadEPa0628** [comment]
> Hello! You may be experiencing network lag or a bug in the game (please send a screenshot of Inspect Element Console). It's also possible that you are not using the right input controls (WASD/arrows/right-click and hold).
> 
> --- google translate ---
> 
> 你好！您可能遇到网络延迟或游戏错误（请发送 Inspect Element Console 的屏幕截图）。也有可能您没有使用正确的输入控件（WASD/箭头/右键单击并按住）。

好的，以下是开发人员工具的截图：
![image](https://github.com/SoftbearStudios/mk48/assets/120295331/5557bae5-d212-4629-aa5c-daf6ca18985b)

**Comment by SadEPa0628** [comment]
> Hello! You may be experiencing network lag or a bug in the game (please send a screenshot of Inspect Element Console). It's also possible that you are not using the right input controls (WASD/arrows/right-click and hold).
> 
> --- google translate ---
> 
> 你好！您可能遇到网络延迟或游戏错误（请发送 Inspect Element Console 的屏幕截图）。也有可能您没有使用正确的输入控件（WASD/箭头/右键单击并按住）。

好的，以下是开发人员工具的截图：
![image](https://github.com/SoftbearStudios/mk48/assets/120295331/9971c379-288d-4776-b97c-1f603318e339)
![image](https://github.com/SoftbearStudios/mk48/assets/120295331/ce7cd0fa-8de7-4f98-8389-3139bf25b6a0)
