### ISSUE TITLE
Player was banned without reason

### ISSUE THREAD

**Issue by SadEPa0628** [SoftbearStudios/mk48#218]
**Describe the bug**

I was sending normal messages in the chat area and the system said "You have been restricted for 18m due to profanity/spam", I wasn't sending profanity or spam, I was just exchanging base information with my teammates.

**Expected behavior**

Optimize the criteria for banning.

**Comment by finnbear** [comment]
In order to investigate, I need your in-game name!

**Comment by finnbear** [comment]
Thanks! I investigated and did find _some_ cases where I didn't understand why you were muted. It may be a profanity filter issue, but I can't read Chinese, so it's hard to tell at a glance what the filter is detecting. I'll revisit this next time I update the profanity filter.

In _other_ cases, you did say mildly inappropriate things or engage in spam.

**Comment by finnbear** [comment]
Nothing in the game prevents you from revealing base coordinates in public chat. If you mean that "Server" told you not to, if the "Server" wasn't in yellow text, it was an impersonator/fake.

**Comment by SadEPa0628** [comment]
I sent a team message stating the location of the base and saying that disclosure is strictly prohibited
