### ISSUE TITLE
Ice reagion being in the wrong area

### ISSUE THREAD

**Issue by alexanderthiem** [SoftbearStudios/mk48#225]
**Describe the bug**

The sun is in the north (specifically north east).  So according to the rules of physik, the north part of the map can't receive less energy from the sun. Still the ice is in the north.

**Expected behavior**

The ice in the north melting slowly and new ice forming in the south, starting with the very next mk48 update.
Or a storyline explicitly stating that the map is on the inside of a sphere and thus the south receives more energy per area,

**Additional context (optional)**

The bug happens on edge, but was verifyed by another player, namely @SeSe008 who participated in discovering the bug.
Further verification missing. Confirmation from other players appreciated.

**Comment by finnbear** [comment]
We never said mk48.io takes place on the planet Earth

**Comment by SeSe008** [comment]
Where does it take place?

**Comment by alexanderthiem** [comment]
Confirmation on being in the inside of an sphere?
