### ISSUE TITLE
Admin config file example

### ISSUE THREAD

**Issue by Stevie0427** [SoftbearStudios/mk48#227]
**Describe the bug**
When I try to deploy my own server, I find that there is a option that can use custon admin config file. But I cannot find the example of admin config file in the github repo.
**Expected behavior**
I would like to know how to configure it and the affect of it.
**Additional context (optional)**
And I would also like to know how to change the size and the landform of the map when deploy my own server.

**Comment by finnbear** [comment]
Here are the variables that you can set in Toml format: https://github.com/SoftbearStudios/mk48/blob/7b5fa7f26f448e9bac0892bc82a18e5fa28713ad/engine/game_server/src/admin.rs#L55-L59

None of them are useful for development or 3rd party servers. In fact, we will be removing all of them in our next open source release.

Note that `password` is related to the admin interface, but the README provides instructions that don't require using the config file: https://github.com/SoftbearStudios/mk48?tab=readme-ov-file#admin-interface-optional

>  And I would also like to know how to change the size and the landform of the map when deploy my own server.

World generation is here: https://github.com/SoftbearStudios/mk48/blob/7b5fa7f26f448e9bac0892bc82a18e5fa28713ad/server/src/noise.rs#L12

Other terrain options are here: https://github.com/SoftbearStudios/mk48/blob/7b5fa7f26f448e9bac0892bc82a18e5fa28713ad/common/src/terrain.rs#L24-L45
