### ISSUE TITLE
Run the game on HTTP port instead of 443

### ISSUE THREAD

**Issue by Stevie0427** [SoftbearStudios/mk48#229]
When I run the game with the varible --http-port , it will automaticlly use the port 443 and redirect the HTTP request to port 443, but the port 443 of my server is used by nginx to deploy some other services. I would likevto know how to deploy the game on an another port instead of 443, thanks.

**Comment by finnbear** [comment]
We have fixed this in our private upstream repository but haven't open-sourced it yet.

Until then, consider editing this line to use whatever port numbers you want: https://github.com/SoftbearStudios/mk48/blob/7b5fa7f26f448e9bac0892bc82a18e5fa28713ad/engine/game_server/src/options.rs#L135

**Comment by Stevie0427** [comment]
OK, so can I disable HTTPS? Because I will use nginx to proxy it and enable HTTPS on the source site make the options more complex.

**Comment by finnbear** [comment]
Hmm, that's a different code change. Go here: https://github.com/SoftbearStudios/mk48/blob/7b5fa7f26f448e9bac0892bc82a18e5fa28713ad/engine/game_server/src/entry_point.rs#L585-L678

Remove all `#[cfg(debug_assertions)]`'s and delete all lines right after `#[cfg(not(debug_assertions))]`'s. Debug was HTTP-only, this change just hardcodes HTTP-only.

**Comment by Stevie0427** [comment]
Thanks for your answering.
