### ISSUE TITLE
Interface for detecting sprites? 

### ISSUE THREAD

**Issue by XenonPy** [SoftbearStudios/mk48#237]
I am attempting to create a tool (as a hobby project) which highlights ships and oil rigs in mk48.io, as a simple example of element tracking. However, mk48.io does not provide any sort of apparent interface that could be inspected by tools like Selenium, as it appears to be a canvas. Is there any workaround/solution to this?

**Comment by finnbear** [comment]
That's cool :)

Mk48 renders to a WebGL 2 canvas. You may be able to use computer vision to recognize things. Intercepting the network protocol or draw calls will be prohibitively difficult.
