### ISSUE TITLE
High Performance Particles

### ISSUE THREAD

**Issue by caibear** [SoftbearStudios/mk48#34]
There are currently only wake particles that are created on the client behind boats. The particles are updated in JS and aren't very fast (~500/ns per update on my computer). This limits the amount of particles that we can spawn and also impacts frame rate on lower end devices. If we can reach at least 100/ns per particle update I think it will meet our goals.

Proposed solutions:
1. Optimize the update code on the CPU by using Web Assembly.
2. Rewrite the particles to be only updated on the GPU with a vertex shader.
3. Reduce the number of particles based on computer specs/frame rate.

Once the particles have high enough performance we can add more effects such as smoke/fire.

**Comment by finnbear** [comment]
I implemented option #3 by scaling particle emissions by FPS.

**Comment by caibear** [comment]
A lot of effects such as fire and smoke are blocked by this. We need to figure out how to get level access to WebGL from PIXI.js so we can implement option 1 or 2. If that can't be done we should look into other methods to do these effects.

**Comment by finnbear** [comment]
Could still be more efficient, but the WebAssembly version is good enough.

**Comment by finnbear** [comment]
Just added smoke to ships and fire to oil rigs. Performance seems fine.
