### ISSUE TITLE
Team chat

### ISSUE THREAD

**Issue by finnbear** [SoftbearStudios/mk48#44]
Teams should be able to talk in private

**Comment by caibear** [comment]
Client:
1. I think holding shift while pressing enter should make a chat message team chat only and/or we could prefix it with /t to be friendly to mobile.
2. Clients would either prefix team chat messages or tint them to make it obvious that they aren't in global chat.

Server:
1. The chat message would have a team chat boolean on it that would cause it to instead be added to the team's chat buffer.
2.  Update message would contain another `[]Chat` for team chats that is set from teams chat buffer.
3.  Teams are iterated and each chat buffer is cleared.
