### ISSUE TITLE
Ship suggestions (list of potential vehicles)

### ISSUE THREAD

**Issue by finnbear** [SoftbearStudios/mk48#55]
## Ships

Planned by @finnbear:
- [x] Zumwalt
- [x] Aircraft carriers (#1)
- [ ] Kirov
- [ ] Typhoon
- [ ] Seawolf
- [ ] Los Angeles
- [x] Yasen
- [x] Town 
- [ ] [Wasp](https://en.wikipedia.org/wiki/USS_Wasp_(LHD-1))
- [x] [Movska](https://en.wikipedia.org/wiki/Moskva-class_helicopter_carrier)
- [ ] [Knox](https://en.wikipedia.org/wiki/Knox-class_frigate)
- [ ] [Maine](https://en.wikipedia.org/wiki/Maine-class_battleship)

Suggested:
- [ ] Ekranoplan (#2)

Suggested by Ranger Falcon:
- [x] Freedom
- [ ] Independence
- [x] Kolkata
- [ ] Iowa (modernized)

Suggested by MuffinMan:
- [ ] HMS Dreadnought

Suggested by FluffieFoxBoi:
- [ ] Repair/resupply ship (#61)

Suggested by Boom:
- [x] Mine-layer (#63)

Suggested by Capt Essex:
- [x] Essex class aircraft carrier
- [ ] Jean Bart

Suggested by BB TRIPZ:
- [ ] Enterprise
- [ ] HMS Hood
- [ ] HMS King George V
- [ ] Sharnhorst

Suggested by Cannon530YT:
- [ ] British seaplane carriers
- [x] Pirate boats

Suggested by Nighthawk:
- [x] Level 6 destroyer
- [ ] Scorpène-class submarine

Suggested by JDUBNUKE:
- [ ] Yamato

Suggested by Ice Ninja:
- [ ] Oil harvesting ship (eco focus)

Suggested by Potato:
- [ ] Iowa

Suggested by Dogg:
- [ ] Yamato
- [ ] Lexington

Suggested by Swbaert6:
- [ ] [Delaware](https://en.wikipedia.org/wiki/Delaware-class_battleship)

## Land vehicles

Planned by @finnbear:
- [ ] Gopher SAM

Suggested by FluffieFoxBoi:
- [ ] Fox (armored reconnaissance vehicle OR M93 Fox)

*You can comment below with more ideas and I'll keep this post updated*

**Comment by Carlsons1938** [comment]
Land Vehicles : Mobile SAM, NDL-40, BM-8-8, LARS

AirCraft          : LZ 120, LZ 127, LZ 13, AC-130, B-2, FW-57, B-29

Ship               : Akizuki, Horizon, Independence, Ægir, Cyclone

Submarine    : SSN 688, SSN 21
