### ISSUE TITLE
Server optimizations

### ISSUE THREAD

**Issue by finnbear** [SoftbearStudios/mk48#6]
World

* [ ] ~~Sector contains an array of entities and a slice/sector pointer for more. (better locality)~~
* [ ] Player has "pointer" to entity. (remove entity ID to entity mapping)
* [x] Shrink entity struct. (better locality and less memory)

Hub

* [x] Clients doubly linked list to other clients. (remove client mapping)
* [x] Shrink Client structs. (less memory)
* [ ] ~~Player has pointer to team. (faster to lookup)~~
* [ ] ~~Player doubly linked list to other players in team. (probably not worth it)~~

Inbound/Outbound

* [ ] Team members and requesting copy on write. (less garbage)
* [ ] Pool inbound messages such as manual. (less garbage)
* [ ] ~~Iterate world to find players rather than iterating players. (better locality)~~
* [x] Send `damage` instead of `health` as it can be omitted more often (crates)

Marshaling

* [ ] Call Stream.Flush less often during marshaling. (up to 15% CPU improvement)
* [ ] Custom float marshaling with less precision. (less network and possibly faster)
* [ ] Terrain compression encoding changes. (less network)
* [ ] ~~Compress packets. (less network but more CPU)~~

**Comment by caibear** [comment]
See #64 for idea number 3.

**Comment by caibear** [comment]
Closing for now. May be reopened in the future.
