### ISSUE TITLE
Mine-layer

### ISSUE THREAD

**Issue by finnbear** [SoftbearStudios/mk48#63]
Suggested by Boom

**Comment by caibear** [comment]
I few questions that I'm wondering about this:
1. Should we have a mine-sweeper or some way of counteracting mines?
2. Is the mine-layer also the mine-sweeper?
3. Are the mines visible for a short amount of time before its too late?
4. Do mines get attracted to ships similar to crates?
5. How long do the mines last?

**Comment by finnbear** [comment]
> I few questions that I'm wondering about this:
> 
>     1. Should we have a mine-sweeper or some way of counteracting mines?

Yes

>     2. Is the mine-layer also the mine-sweeper?

At least for now; probably forever. No use having 2 mine-related support ships when there could be one, other than realism.

>     3. Are the mines visible for a short amount of time before its too late?

Yes, like all underwater weapons

>     4. Do mines get attracted to ships similar to crates?

Probably yes.

>     5. How long do the mines last?

Mines should last the same order of magnitude as long as the terrain they are designed to protect, so maybe 20-40 minutes.
