### ISSUE TITLE
Convert altitude to int8 and apply it to all entities

### ISSUE THREAD

**Issue by finnbear** [SoftbearStudios/mk48#76]

**Comment by caibear** [comment]
I don't think each entity should have an altitude (only boats).
I'm not against making it an `int8`.

**Comment by finnbear** [comment]
Problems that can be solved by giving a non-boat entity altitude:
- Airdropped torpedoes don't move and get a parachute before they hit the water
- Torpedoes start at launch depth and rise/descend to target depth (no point blank submerged sub vs battleship torpedoes)
- Submarine launched missile must rise to the surface first (if the submarine is deep), making them less overpowered
- Depth charges sink to the bottom, instead of instantly hitting submerged submarines

**Comment by finnbear** [comment]
Done.
