### ISSUE TITLE
Random websocket disconnect

### ISSUE THREAD

**Issue by finnbear** [SoftbearStudios/mk48#79]
Happened twice now (in a week), second time debug logging implemented, code 1006

**Comment by caibear** [comment]
Could be caused by server disconnecting if it has more than `1.5s` of messages in the buffer.
We could make it use a counter and drop all the messages for up to `10s`.

**Comment by finnbear** [comment]
Server now throttles messages as the buffer nears capacity. Closing until reproduced.
